[package]
name = "feuerfreund"
version = "0.2.0"
edition = "2021"
description = "Imbue your discord voice chat with a crackling flame"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenvy = "0.15.7"
poise = { version = "0.5.5", features = ["cache"] }
rand = "0.8.5"
serenity = { version = "0.11.6", default-features = false, features = ["http", "native_tls_backend", "voice"] }
songbird = "0.3.2"
time = { version = "0.3.28", features = ["macros"] }
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["fmt", "std", "time", "env-filter"]}
