name: build and push

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: run sccache
        uses: mozilla-actions/sccache-action@v0.0.3

      - uses: actions/checkout@v4

      - run: cargo check --release
      - run: cargo clippy --release

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/fxqnlr/feuerfreund:latest
            ghcr.io/fxqnlr/feuerfreund:${{ github.run_number }}
